name: CheatArmor
main: georgianYT\CheatArmor\Main
authors: georgianYT and Pocketmine-PHP
description: Plugin to make yours armors Ultra cheat perfect for Factions servers and MiniGames
version: 0.2
api: [3.0.0, 3.2.0]
website: https://github.com/georgianYT
